---
output: 
  html_document: 
    keep_md: yes
---
# Statistical Rethinking Chapter 3 problems

__Name:_Sharon Gray_

## 3E1
```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 ) 
prior <- rep( 1 , 1000 ) 
likelihood <- dbinom( 6 , size=9 , prob=p_grid ) 
posterior <- likelihood * prior 
posterior <- posterior / sum(posterior) 
set.seed(100) 
samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )
sum( samples < 0.2 ) / 1e4 #How much posterior prob lies below p=0.2?
```
## 3E2
```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 ) 
prior <- rep( 1 , 1000 ) 
likelihood <- dbinom( 6 , size=9 , prob=p_grid ) 
posterior <- likelihood * prior 
posterior <- posterior / sum(posterior) 
set.seed(100) 
samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )
sum( samples > 0.8 ) / 1e4 #How much posterior prob lies above p=0.8?
```
## 3E3
```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 ) 
prior <- rep( 1 , 1000 ) 
likelihood <- dbinom( 6 , size=9 , prob=p_grid ) 
posterior <- likelihood * prior 
posterior <- posterior / sum(posterior) 
set.seed(100) 
samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )
sum( samples >0.2 & samples < 0.8 ) / 1e4 #How much posterior prob lies between p=0.2 & p=0.8?
```
## 3E4
```{r}
quantile( samples , 0.2 ) #20% of the posterior probability lies below which value of p?
```
## 3E5
```{r}
quantile( samples , 0.8 ) #20% of the posterior probability lies above which value of p?
```
## 3E6
```{r}
library(rethinking)
HPDI( samples , prob=0.66 ) #Which values of p contain the narrowest interval equal to 66% of the posterior probability?
```
## 3E7
```{r}
PI( samples , prob=0.66 ) #Which values of p contain 66% of the posterior probability, assuming equal posterior probability both below and above the interval?
```
## 3M1
```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 ) 
prior <- rep( 1 , 1000 ) 
likelihood <- dbinom( 8 , size=15 , prob=p_grid ) 
posterior <- likelihood * prior 
posterior <- posterior / sum(posterior) 
set.seed(100) 
samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )
hist(samples)
```
## 3M2
```{r}
samples2 <- sample( p_grid , prob=posterior , size=10000 , replace=TRUE)
HPDI( samples2 , prob=0.90 )
hist(samples2)
abline(v=HPDI(samples2, prob=0.90)[1], col="blue", lwd=2.5)
abline(v=HPDI(samples2, prob=0.90)[2], col="blue", lwd=2.5)
```

## 3M3
```{r}
dummy_w <- rbinom( 1e5 , size=15 , prob=samples )
table(dummy_w)/1e5
simplehist(dummy_w, xlab="dummy data water")
```
The probability of observing 8 water in 15 tosses is 14.6%.
## 3M4
```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 ) 
prior <- rep( 1 , 1000 ) 
dummy_prob <- (dummy_w)/1e5
likelihood <- dbinom( 6 , size=9 , prob=dummy_prob ) 
posterior <- likelihood * prior 
posterior <- posterior / sum(posterior) 
plot(posterior, dummy_prob)

```
## 3M5
```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 ) 
prior <- c(rep( 0, 500) , rep(1, 500)) 
likelihood <- dbinom( 8 , size=15 , prob=p_grid ) 
posterior <- likelihood * prior 
posterior <- posterior / sum(posterior) 
set.seed(100) 
samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )
hist(samples)
samples2 <- sample( p_grid , prob=posterior , size=10000 , replace=TRUE)
HPDI( samples2 , prob=0.90 )
hist(samples2)
abline(v=HPDI(samples2, prob=0.90)[1], col="blue", lwd=2.5)
abline(v=HPDI(samples2, prob=0.90)[2], col="blue", lwd=2.5)
dummy_w <- rbinom( 1e5 , size=15 , prob=samples2 )
table(dummy_w)/1e5
simplehist(dummy_w, xlab="dummy data water")
```
Now the probability of 8 water in 15 tosses is greater (15.8%) 
## 3H1

```{r}
library(rethinking) 
data(homeworkch3)
sum(birth1) + sum(birth2)
p_grid <- seq( from=0 , to=1 , length.out=1000 )
likelihood <- dbinom(111, size=200, prob=p_grid)
posterior <- likelihood * prior 
posterior <- posterior / sum(posterior)
loss <- sapply( p_grid , function(d) sum( posterior*abs( d - p_grid)))
p_grid[which.min(loss)]
```
0.55
## 3H2
```{r}
samples2 <- sample( p_grid , prob=posterior , size=10000 , replace=TRUE)
HPDI( samples2 , prob=0.50 )
HPDI( samples2 , prob=0.89 )
HPDI( samples2 , prob=0.97 )
hist(samples2)
```
## 3H3
```{r}
w <- rbinom( 10000 , size=200 , prob=samples2 )
dens(w)
abline(v=111)
```
## 3H4
```{r}
sum(birth1)
w2 <- rbinom( 10000 , size=100 , prob=samples2 )
dens(w2)
abline(v=51)
```
bad model.
## 3H5
```{r}
girls <- 100-sum(birth1)
girlsfirst <- birth2[which(birth1==0)]
sum(girlsfirst)
sum(girlsfirst)/length(girlsfirst)
w3 <- rbinom( 10000 , size=49 , prob=samples2 )
dens(w3)
abline(v=39)
table(w3)/10000

```
Boys are more likely after the first birth is a girl.
The probability of getting 39 girl-boy events is only 0.0013, under the flat prior, and assuming the births were independent.